### ISSUE TITLE
[QUESTION] How to use grid snapping ?

### ISSUE THREAD

**Issue by quentin-sommer** [sporritt/jsPlumb#528]
Hi,

I've tried to make it work like this:

```javascript
var instance = jsPlumb.getInstance();
instance.setContainer($("#jsPlumb"));
instance.draggable($(".box"), {
    grid: [10, 10]
});
```

where `#jsPlumb` is my container and `.box` a class applied to every item inside the container
```css
#jsPlumb {
  height: 1000px;
  position: relative !important;
  background-color: lightblue;
}

.box {
  position: absolute;
  width: 150px;
  height: 100px;
  border: 2px solid black;
}
```

However it doesn't snap at all! Any advice ?
